# Generated by Django 3.0.4 on 2020-04-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsapp', '0002_auto_20200407_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(null=True)),
                ('speciality', models.CharField(default='General Physician', max_length=25)),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('details', models.CharField(max_length=150)),
            ],
        ),
    ]
