# Generated by Django 3.0.4 on 2020-04-21 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsapp', '0007_customuser_is_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_employee',
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(max_length=200)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsapp.Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('scheduled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsapp.DoctorSchedule')),
            ],
        ),
    ]
