# Generated by Django 3.0.4 on 2020-04-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsapp', '0008_auto_20200421_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='snu_id',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
