# Generated by Django 3.0.4 on 2020-04-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsapp', '0010_appointments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='details',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
