# Generated by Django 3.0.4 on 2020-04-24 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsapp', '0011_auto_20200424_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='snu_id',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='details',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
