# Generated by Django 3.0.4 on 2020-04-25 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsapp', '0012_auto_20200425_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='medicines',
            name='image',
        ),
    ]
