# Generated by Django 3.0.4 on 2020-04-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsapp', '0013_auto_20200425_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorschedule',
            name='day',
            field=models.CharField(default='Monday', max_length=10),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
