# Generated by Django 3.0.4 on 2020-04-25 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsapp', '0014_auto_20200426_0115'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointments',
            unique_together={('patient', 'doctor', 'scheduled', 'date')},
        ),
    ]
