# Generated by Django 3.0.4 on 2020-05-02 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsapp', '0015_auto_20200426_0130'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointments',
            unique_together={('patient', 'scheduled', 'date')},
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='doctor',
        ),
    ]
